// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.EFCore.ClaimDataModels
{
    public partial class ClaimDataContext : DbContext
    {
        public ClaimDataContext()
        {
        }

        public ClaimDataContext(DbContextOptions<ClaimDataContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Approvalregis> Approvalregis { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Approvalregis>(entity =>
            {
                entity.HasKey(e => new { e.CrClaimno, e.VVictimno, e.ApRegno })
                    .IsClustered(false);

                entity.ToTable("APPROVALREGIS");

                entity.HasIndex(e => e.AccAppNo)
                    .HasName("xApprovalRegis_AccAppNo");

                entity.HasIndex(e => e.AccNo)
                    .HasName("xApprovalRegis_AccNo");

                entity.HasIndex(e => e.AccVictimNo)
                    .HasName("xApprovalRegis_AccVictimNo");

                entity.HasIndex(e => e.ApApproveby)
                    .HasName("xApprovedBy");

                entity.HasIndex(e => e.ApApprovedate)
                    .HasName("MFEC_IndexAP_ApproveDate");

                entity.HasIndex(e => e.ApCf014)
                    .HasName("cf014");

                entity.HasIndex(e => e.ApHosid)
                    .HasName("xAP_Hosid");

                entity.HasIndex(e => e.ApPaymore)
                    .HasName("XPayMore");

                entity.HasIndex(e => e.ApRecfname)
                    .HasName("MFEC_IndexAP_RecFName");

                entity.HasIndex(e => e.ApReclname)
                    .HasName("MFEC_IndexAP_RecLName");

                entity.HasIndex(e => e.ApRegdate);

                entity.HasIndex(e => e.ApRegno)
                    .HasName("MFEC_IndexAP_RegNo");

                entity.HasIndex(e => e.ApStatus)
                    .HasName("apstatus");

                entity.HasIndex(e => e.ApTransbranch)
                    .HasName("XTransBranch");

                entity.HasIndex(e => e.CrClaimno)
                    .HasName("claimno");

                entity.HasIndex(e => e.CvVoucherno)
                    .HasName("XVoucherNo");

                entity.HasIndex(e => e.VVictimno)
                    .HasName("MFEC_IndexV_VictimNo");

                entity.HasIndex(e => new { e.CvVoucherno, e.ApTransbranch, e.ApMoney })
                    .HasName("Viva_CLManipulateAcceptPaidbyMgr_Idx3");

                entity.HasIndex(e => new { e.ApTransbranch, e.ApStatus, e.ApHosid, e.ApMoneydate })
                    .HasName("Viva_CLPaidMoneyReport_Idx1");

                entity.HasIndex(e => new { e.CrClaimno, e.ApEntrydate, e.ApStatus, e.ApMoney })
                    .HasName("Viva_spCLRCReportInsuranceDebt_Idx1");

                entity.HasIndex(e => new { e.CrClaimno, e.VVictimno, e.ApPaytype, e.ApMoney, e.ApTransbranch, e.ApMoneydate })
                    .HasName("Viva_CLPaidByVictimBrokenReport_Idx1");

                entity.HasIndex(e => new { e.CrClaimno, e.VVictimno, e.ApRegno, e.ApEntrydate, e.ApStatus, e.ApMoney })
                    .HasName("Viva_spCLRCReportInsuranceDebt_Idx3");

                entity.HasIndex(e => new { e.CrClaimno, e.VVictimno, e.ApRegno, e.ApMoney, e.ApMoneydate, e.ApStatus })
                    .HasName("Viva_AP_STATUS");

                entity.HasIndex(e => new { e.CrClaimno, e.VVictimno, e.ApRegno, e.CvVoucherno, e.ApTransbranch, e.ApMoney })
                    .HasName("Viva_CLManipulateAcceptPaidbyMgr_Idx2");

                entity.HasIndex(e => new { e.CrClaimno, e.VVictimno, e.ApRegno, e.ApMoney, e.ApRecfname, e.ApReclname, e.ApHosid, e.ApStatus })
                    .HasName("Viva_Au_ScanAbclaim_Idx1");

                entity.Property(e => e.CrClaimno)
                    .HasColumnName("CR_CLAIMNO")
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasComment("เลขเคลม");

                entity.Property(e => e.VVictimno)
                    .HasColumnName("V_VICTIMNO")
                    .HasComment("ลำดับผู้ประสบภัย");

                entity.Property(e => e.ApRegno)
                    .HasColumnName("AP_REGNO")
                    .HasComment("ลำดับคำร้อง");

                entity.Property(e => e.AccAppNo).HasComment("ลำดับคำร้องของรับแจ้ง");

                entity.Property(e => e.AccNo)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("เลขรับแจ้ง");

                entity.Property(e => e.AccVictimNo).HasComment("ลำดับผู้ประสบภัยของรับแจ้ง");

                entity.Property(e => e.ApApproveby)
                    .HasColumnName("AP_APPROVEBY")
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasComment("ผู้อนุมัติ");

                entity.Property(e => e.ApApprovedate)
                    .HasColumnName("AP_APPROVEDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่อนุมัติ");

                entity.Property(e => e.ApCf014)
                    .HasColumnName("Ap_CF014")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('N')")
                    .HasComment("การยืนยันความคุ้มครอง KCL014");

                entity.Property(e => e.ApCf014Comment)
                    .HasColumnName("Ap_Cf014Comment")
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasComment("หมายเหตุการยืนยัน KCL014");

                entity.Property(e => e.ApCf014Date)
                    .HasColumnName("Ap_Cf014Date")
                    .HasColumnType("datetime")
                    .HasComment("วันที่ยืนยันความคุ้มครอง KCL014");

                entity.Property(e => e.ApCf014Money)
                    .HasColumnName("Ap_cf014Money")
                    .HasComment("จำนวนเงินที่IOCยืนยันให้จ่าย");

                entity.Property(e => e.ApCf014user)
                    .HasColumnName("Ap_CF014USER")
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasComment("ผู้ยืนยันความคุ้มครอง KCL014");

                entity.Property(e => e.ApClearBy)
                    .HasColumnName("AP_ClearBy")
                    .HasMaxLength(6)
                    .IsUnicode(false);

                entity.Property(e => e.ApClearDate)
                    .HasColumnName("AP_ClearDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApConcat)
                    .HasColumnName("ap_concat")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ApDataStatus)
                    .HasColumnName("Ap_DataStatus")
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasDefaultValueSql("('N')");

                entity.Property(e => e.ApDiscount)
                    .HasColumnName("Ap_Discount")
                    .HasColumnType("money")
                    .HasComment("ส่วนลด");

                entity.Property(e => e.ApDuedate)
                    .HasColumnName("AP_DUEDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApEntryby)
                    .HasColumnName("AP_ENTRYBY")
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasComment("ผู้บันทึก");

                entity.Property(e => e.ApEntrydate)
                    .HasColumnName("AP_ENTRYDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่บันทึก");

                entity.Property(e => e.ApHosid)
                    .HasColumnName("AP_HOSID")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasComment("รหัสรพ.ที่รับเงิน");

                entity.Property(e => e.ApHosidprov)
                    .HasColumnName("AP_HOSIDPROV")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasComment("รหัสจังหวัดรพ.ที่รับเงิน");

                entity.Property(e => e.ApInsertDate)
                    .HasColumnName("Ap_InsertDate")
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ApInvoice)
                    .HasColumnName("AP_INVOICE")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ApLastupdate)
                    .HasColumnName("AP_LASTUPDATE")
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())")
                    .HasComment("วันที่ปรับปรุงข้อมูลล่าสุด");

                entity.Property(e => e.ApMoney)
                    .HasColumnName("AP_MONEY")
                    .HasColumnType("money")
                    .HasComment("จำนวนเงิน");

                entity.Property(e => e.ApMoneydate)
                    .HasColumnName("AP_MONEYDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่จ่าย");

                entity.Property(e => e.ApMoreapproveby)
                    .HasColumnName("AP_MOREAPPROVEBY")
                    .HasMaxLength(8)
                    .IsUnicode(false);

                entity.Property(e => e.ApMoreapprovedate)
                    .HasColumnName("AP_MOREAPPROVEDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApMoreapproveid)
                    .HasColumnName("AP_MOREAPPROVEID")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.ApMorecode)
                    .HasColumnName("AP_MORECODE")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ApPayBackComment)
                    .HasColumnName("Ap_PayBackComment")
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasComment("หมายเหตุการบันทึกรับเงินคืน");

                entity.Property(e => e.ApPaymore)
                    .HasColumnName("AP_PAYMORE")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("เบื้องต้น ส่วนเกิน N=เบื้องต้น Y=ส่วนเกิน B=เบื้องต้นและส่วนเกิน");

                entity.Property(e => e.ApPaytype)
                    .HasColumnName("AP_PAYTYPE")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("การจ่าย");

                entity.Property(e => e.ApRcIoc).HasColumnName("ap_RcIoc");

                entity.Property(e => e.ApRecfname)
                    .HasColumnName("AP_RECFNAME")
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("ชื่อผู้รับเงิน");

                entity.Property(e => e.ApRecid)
                    .HasColumnName("AP_RECID")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("เลขประจำตัวผู้รับเงิน");

                entity.Property(e => e.ApReciddist)
                    .HasColumnName("AP_RECIDDIST")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.ApRecidprov)
                    .HasColumnName("AP_RECIDPROV")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.ApReclname)
                    .HasColumnName("AP_RECLNAME")
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("นามสกุลผู้รับเงิน");

                entity.Property(e => e.ApRecnationalityId).HasColumnName("AP_RECNationalityID");

                entity.Property(e => e.ApRecprefix)
                    .HasColumnName("AP_RECPREFIX")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("คำนำหน้าผู้รับเงิน");

                entity.Property(e => e.ApRecrelate)
                    .HasColumnName("AP_RECRELATE")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasComment("รหัสความสัมพันธ์ผู้รับเงิน");

                entity.Property(e => e.ApRegdate)
                    .HasColumnName("AP_REGDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่ยื่นคำร้อง");

                entity.Property(e => e.ApRegtype)
                    .HasColumnName("AP_REGTYPE")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("ประเภทการจ่าย F=Full ,P=Partial");

                entity.Property(e => e.ApRevfname)
                    .HasColumnName("AP_REVFNAME")
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("ชื่อผู้ยื่นคำร้อง");

                entity.Property(e => e.ApRevfullname)
                    .HasColumnName("AP_REVFULLNAME")
                    .HasMaxLength(110)
                    .IsUnicode(false);

                entity.Property(e => e.ApRevlname)
                    .HasColumnName("AP_REVLNAME")
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("นามสกุลผู้ยื่นคำร้อง");

                entity.Property(e => e.ApRevprefix)
                    .HasColumnName("AP_REVPREFIX")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("คำนำหน้าผู้ยื่นคำร้อง");

                entity.Property(e => e.ApRevrelate)
                    .HasColumnName("AP_REVRELATE")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasComment("รหัสความสัมพันธ์ผู้ยื่นคำร้อง");

                entity.Property(e => e.ApRvpInvoice)
                    .HasColumnName("Ap_RvpInvoice")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ApSenddate)
                    .HasColumnName("AP_SENDDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApSendstatus)
                    .HasColumnName("AP_SENDSTATUS")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ApStatus)
                    .HasColumnName("AP_STATUS")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasDefaultValueSql("('R')");

                entity.Property(e => e.ApSummaryFlag)
                    .HasColumnName("Ap_SummaryFlag")
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.ApSummaryPaid)
                    .HasColumnName("ap_SummaryPaid")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.ApTid)
                    .HasColumnName("AP_TID")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasDefaultValueSql("('0')");

                entity.Property(e => e.ApTidSend)
                    .HasColumnName("ap_TidSend")
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.ApTiddate)
                    .HasColumnName("AP_TIDDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApTotal)
                    .HasColumnName("Ap_Total")
                    .HasColumnType("money")
                    .HasComment("จำนวนเงินรวม");

                entity.Property(e => e.ApTransbranch)
                    .HasColumnName("AP_TRANSBRANCH")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasComment("สาขาที่จ่าย");

                entity.Property(e => e.ApTranstype)
                    .HasColumnName("AP_TRANSTYPE")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ApUpdateDate)
                    .HasColumnName("Ap_UpdateDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.ApVtmhos)
                    .HasColumnName("AP_VTMHOS")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("H=Hospital, V=Victim");

                entity.Property(e => e.Comment)
                    .HasMaxLength(120)
                    .IsUnicode(false)
                    .HasComment("หมายเหตุต่างๆ เช่นการเรียกร้อง");

                entity.Property(e => e.CvVoucherno)
                    .HasColumnName("CV_VOUCHERNO")
                    .HasMaxLength(14)
                    .IsUnicode(false)
                    .HasComment("เลขที่ CV");

                entity.Property(e => e.CvpaidType)
                    .HasColumnName("CVPaidType")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.DailyReceiveno)
                    .HasColumnName("daily_receiveno")
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("เลขที่ใบเสร็จ");

                entity.Property(e => e.HospitalidTreat)
                    .HasColumnName("hospitalidTreat")
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.InvoiceEclaim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("เลขที่ใบแจ้งหนี้");

                entity.Property(e => e.MCardType)
                    .HasColumnName("mCardType")
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasComment("ประเภทบัตร");

                entity.Property(e => e.MCardTypeOther)
                    .HasColumnName("mCardTypeOther")
                    .HasMaxLength(250)
                    .IsUnicode(false)
                    .HasComment("ประเภทบัตรอื่นๆ");

                entity.Property(e => e.Pt4)
                    .HasColumnName("PT4")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("บต.");

                entity.Property(e => e.RecInsId)
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.RecoverySpecialStatus)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.RegisbyBranch)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}