// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.EFCore.iPolicyModels
{
    public partial class IpolicyContext : DbContext
    {
        public IpolicyContext()
        {
        }

        public IpolicyContext(DbContextOptions<IpolicyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DirectPolicyKyc> DirectPolicyKyc { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DirectPolicyKyc>(entity =>
            {
                entity.HasKey(e => e.Kycno);

                entity.ToTable("DirectPolicy_KYC");

                entity.Property(e => e.Kycno)
                    .HasColumnName("KYCNo")
                    .ValueGeneratedNever();

                entity.Property(e => e.CurrentAddrIsHomeAddr)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.CurrentBuildingName)
                    .HasColumnName("Current_BuildingName")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentCityId)
                    .HasColumnName("Current_CityID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentHmo)
                    .HasColumnName("Current_HMO")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentHouseNo)
                    .HasColumnName("Current_HouseNo")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentProvinceId)
                    .HasColumnName("Current_ProvinceID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentRoad)
                    .HasColumnName("Current_Road")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentSoi)
                    .HasColumnName("Current_Soi")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentTumbolId)
                    .HasColumnName("Current_TumbolID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.CurrentZipcode)
                    .HasColumnName("Current_Zipcode")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.DateofBirth).HasColumnType("datetime");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Fname)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Gender)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.HashData)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.HomeBuildingName)
                    .HasColumnName("Home_BuildingName")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.HomeCityId)
                    .HasColumnName("Home_CityID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.HomeHmo)
                    .HasColumnName("Home_HMO")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.HomeHouseNo)
                    .HasColumnName("Home_HouseNo")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.HomeProvinceId)
                    .HasColumnName("Home_ProvinceID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.HomeRoad)
                    .HasColumnName("Home_Road")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.HomeSoi)
                    .HasColumnName("Home_Soi")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.HomeTumbolId)
                    .HasColumnName("Home_TumbolID")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.HomeZipcode)
                    .HasColumnName("Home_Zipcode")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.IdcardLaserCode)
                    .HasColumnName("IDCardLaserCode")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.IdcardNo)
                    .HasColumnName("IDCardNo")
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.Property(e => e.InsertDate).HasColumnType("datetime");

                entity.Property(e => e.LastUpdateDate).HasColumnType("datetime");

                entity.Property(e => e.LastUpdateIp)
                    .HasColumnName("LastUpdateIP")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LineId)
                    .HasColumnName("LineID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LineRegisDate).HasColumnType("datetime");

                entity.Property(e => e.LineRegisIp)
                    .HasColumnName("LineRegisIP")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Lname)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.MobileNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Password)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Prefix)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Status)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.UserToken)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Username)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.WebRegisDate).HasColumnType("datetime");

                entity.Property(e => e.WebRegisIp)
                    .HasColumnName("WebRegisIP")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}