// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Services.Models
{
    public partial class District
    {
        public string Amphurid { get; set; }
        public string Amphurname { get; set; }
    }
}