// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.EFCore.PVRModels
{
    public partial class PVRContext : DbContext
    {
        public PVRContext()
        {
        }

        public PVRContext(DbContextOptions<PVRContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Epolicy> Epolicy { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Epolicy>(entity =>
            {
                entity.HasKey(e => e.Seq)
                    .IsClustered(false);

                entity.ToTable("EPOLICY");

                entity.HasIndex(e => e.Agentid)
                    .HasName("XP_AGENTID");

                entity.HasIndex(e => e.Apno)
                    .HasName("XP_APNO");

                entity.HasIndex(e => e.Branchid)
                    .HasName("bid");

                entity.HasIndex(e => e.Canceldate)
                    .HasName("idxcanceldate");

                entity.HasIndex(e => e.Carno)
                    .HasName("Carno");

                entity.HasIndex(e => e.Cartankno)
                    .HasName("XP_CARTANKNO");

                entity.HasIndex(e => e.Closeperiod)
                    .HasName("closeperiodidx");

                entity.HasIndex(e => e.Enddate)
                    .HasName("enddate");

                entity.HasIndex(e => e.Firstname)
                    .HasName("fname");

                entity.HasIndex(e => e.Idcard)
                    .HasName("XP_IDCard");

                entity.HasIndex(e => e.Kum025id)
                    .HasName("XP_KUM025ID");

                entity.HasIndex(e => e.Lineagent)
                    .HasName("XP_LineAgent");

                entity.HasIndex(e => e.Pamphur)
                    .HasName("pamphur");

                entity.HasIndex(e => e.Pchangwat)
                    .HasName("pchangwat");

                entity.HasIndex(e => e.Policydate);

                entity.HasIndex(e => e.Policyno)
                    .HasName("PolicyNo")
                    .IsUnique();

                entity.HasIndex(e => e.Receiptno)
                    .HasName("XP_RECEIPTNO");

                entity.HasIndex(e => e.Returnpremium)
                    .HasName("MFEC_returnpremium");

                entity.HasIndex(e => e.Stampdate)
                    .HasName("Viva_EStampDate");

                entity.HasIndex(e => e.Startdate)
                    .HasName("startdate");

                entity.HasIndex(e => e.Status)
                    .HasName("XP_STATUS");

                entity.HasIndex(e => e.Statusdate)
                    .HasName("statusdateidx");

                entity.HasIndex(e => e.Surname)
                    .HasName("sname");

                entity.HasIndex(e => e.Vatdate)
                    .HasName("vatdate");

                entity.HasIndex(e => new { e.Policyno, e.Status })
                    .HasName("Viva_Status_Idx1");

                entity.HasIndex(e => new { e.Statusdate, e.Policydate })
                    .HasName("Viva_PolicyDate");

                entity.HasIndex(e => new { e.Policydate, e.Kum025id, e.Agentid, e.Startdate, e.Enddate, e.Lineagent, e.Status })
                    .HasName("Viva_ums_UpdateCreditline_idx1");

                entity.HasIndex(e => new { e.Firstname, e.Surname, e.Cartankno, e.Carno, e.Carchangwat, e.Policyno, e.Startdate, e.Enddate, e.Pcartype, e.Policydate, e.Status })
                    .HasName("Viva_Qrepolicy_idx1");

                entity.HasIndex(e => new { e.Firstname, e.Surname, e.Addr, e.Telephoneno, e.Titlename, e.Pchangwat, e.Pzipcode, e.Enginesize, e.Ptotal, e.Cartankno, e.Carno, e.Startdate, e.Starttime, e.Enddate, e.Pcartype, e.Marque, e.Commission, e.Idcard, e.Agentid, e.Policydate, e.Stickerid, e.Status, e.Carchangwat, e.Seq, e.Branchid, e.Policyno })
                    .HasName("x_EPOLICY_7_12731_");

                entity.Property(e => e.Seq)
                    .HasColumnName("SEQ")
                    .HasComment("ลำดับ");

                entity.Property(e => e.Activedays)
                    .HasColumnName("activedays")
                    .HasComment("จำนวนวันที่คุ้มครอง");

                entity.Property(e => e.Addr)
                    .HasColumnName("ADDR")
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasComment("ที่อยู่");

                entity.Property(e => e.Agentid)
                    .HasColumnName("AGENTID")
                    .HasMaxLength(16)
                    .IsUnicode(false)
                    .HasComment("รหัสตัวแทน");

                entity.Property(e => e.Apno)
                    .HasColumnName("APNO")
                    .HasMaxLength(14)
                    .IsUnicode(false);

                entity.Property(e => e.Branchid)
                    .HasColumnName("BRANCHID")
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasComment("รหัสสาขา");

                entity.Property(e => e.Canceldate)
                    .HasColumnName("CANCELDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่ยกเลิก");

                entity.Property(e => e.Canceltype)
                    .HasColumnName("CANCELTYPE")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Carchangwat)
                    .HasColumnName("CARCHANGWAT")
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasComment("จังหวัดทะเบียนรถ");

                entity.Property(e => e.Carcolor)
                    .HasColumnName("CARCOLOR")
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.Carmodel)
                    .HasColumnName("CARMODEL")
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.Carno)
                    .HasColumnName("CARNO")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("ทะเบียนรถ");

                entity.Property(e => e.Cartankno)
                    .HasColumnName("CARTANKNO")
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasComment("เลขตัวถัง");

                entity.Property(e => e.Closeperiod)
                    .HasColumnName("CLOSEPERIOD")
                    .HasColumnType("datetime")
                    .HasComment("วันที่ปิดงวด");

                entity.Property(e => e.Commission)
                    .HasColumnName("commission")
                    .HasComment("ค่าคอมมิชชัน");

                entity.Property(e => e.Ctype)
                    .HasColumnName("CType")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Enddate)
                    .HasColumnName("ENDDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่สิ้นสุดความคุ้มครอง");

                entity.Property(e => e.Enginesize)
                    .HasColumnName("ENGINESIZE")
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("ขนาดรถ");

                entity.Property(e => e.Firstname)
                    .HasColumnName("FIRSTNAME")
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("ชื่อ");

                entity.Property(e => e.Hmo)
                    .HasColumnName("HMO")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.Idcard)
                    .HasColumnName("IDCard")
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasComment("รหัสบัตรปชช");

                entity.Property(e => e.Keydate)
                    .HasColumnName("KEYDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่บันทึก");

                entity.Property(e => e.Keytime)
                    .HasColumnName("KEYTIME")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("เวลาที่บันทึก");

                entity.Property(e => e.Kum025id)
                    .HasColumnName("KUM025ID")
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.Kum038)
                    .HasColumnName("KUM038")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Kum038serial)
                    .HasColumnName("KUM038SERIAL")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Lineagent)
                    .HasColumnName("LINEAGENT")
                    .HasMaxLength(16)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Linecommission).HasColumnName("linecommission");

                entity.Property(e => e.Marque)
                    .HasColumnName("MARQUE")
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasComment("ยี่ห้อรถ");

                entity.Property(e => e.Oldstickerid)
                    .HasColumnName("oldstickerid")
                    .HasMaxLength(11)
                    .IsUnicode(false);

                entity.Property(e => e.Pamphur)
                    .HasColumnName("PAMPHUR")
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasComment("อำเภอ");

                entity.Property(e => e.Pcartype)
                    .HasColumnName("PCARTYPE")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasComment("รหัสรถ");

                entity.Property(e => e.Pchangwat)
                    .HasColumnName("PCHANGWAT")
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasComment("จังหวัด");

                entity.Property(e => e.Policydate)
                    .HasColumnName("POLICYDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่ขาย");

                entity.Property(e => e.Policyno)
                    .HasColumnName("POLICYNO")
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasComment("เลขกรมธรรม์");

                entity.Property(e => e.Ppremium)
                    .HasColumnName("PPREMIUM")
                    .HasComment("เบี้ยประกัน");

                entity.Property(e => e.Pstamp)
                    .HasColumnName("PSTAMP")
                    .HasComment("อากร");

                entity.Property(e => e.Ptotal)
                    .HasColumnName("PTOTAL")
                    .HasComment("รวมเงิน");

                entity.Property(e => e.Ptumbol)
                    .HasColumnName("PTUMBOL")
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasComment("ตำบล");

                entity.Property(e => e.Pvat)
                    .HasColumnName("PVAT")
                    .HasComment("ภาษี");

                entity.Property(e => e.Pvatrate).HasColumnName("PVATRATE");

                entity.Property(e => e.Pzipcode)
                    .HasColumnName("PZIPCODE")
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasComment("รหัสไปรษณีย์");

                entity.Property(e => e.Receiptno)
                    .HasColumnName("RECEIPTNO")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Regionid)
                    .HasColumnName("REGIONID")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength()
                    .HasComment("รหัสภาค");

                entity.Property(e => e.Repay)
                    .HasColumnType("decimal(10, 2)")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.Returnpremium).HasColumnName("RETURNPREMIUM");

                entity.Property(e => e.Road)
                    .HasColumnName("ROAD")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("ถนน");

                entity.Property(e => e.Sflg)
                    .HasColumnName("SFLG")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Stampdate)
                    .HasColumnName("STAMPDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.Startdate)
                    .HasColumnName("STARTDATE")
                    .HasColumnType("datetime")
                    .HasComment("วันที่คุ้มครอง");

                entity.Property(e => e.Starttime)
                    .HasColumnName("STARTTIME")
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasComment("เวลาเริ่มคุ้มครอง");

                entity.Property(e => e.Status)
                    .HasColumnName("STATUS")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasComment("สถานะ");

                entity.Property(e => e.Statusdate)
                    .HasColumnName("STATUSDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.Stickerid)
                    .HasColumnName("STICKERID")
                    .HasMaxLength(11)
                    .IsUnicode(false);

                entity.Property(e => e.Stickerreceivedate)
                    .HasColumnName("STICKERRECEIVEDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.Surname)
                    .HasColumnName("SURNAME")
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasComment("สกุล");

                entity.Property(e => e.Telephoneno)
                    .HasColumnName("TELEPHONENO")
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasComment("เบอร์โทร");

                entity.Property(e => e.Titlename)
                    .HasColumnName("TITLENAME")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasComment("คำนำหน้า");

                entity.Property(e => e.Userid)
                    .HasColumnName("USERID")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasComment("ชื่อผู้ใช้");

                entity.Property(e => e.Vat)
                    .HasColumnName("VAT")
                    .HasColumnType("decimal(10, 2)")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.Vatdate)
                    .HasColumnName("VATDATE")
                    .HasColumnType("datetime");

                entity.Property(e => e.Wht)
                    .HasColumnName("WHT")
                    .HasColumnType("decimal(10, 2)")
                    .HasDefaultValueSql("((0))");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}