// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.BankNamesModels
{
    public partial class BankNames
    {
        public string Bank { get; set; }
        public string Name { get; set; }
        public string Default0 { get; set; }
        public string BankCode { get; set; }

    
    }
}