// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Amphur
    {
        public string Amphurid { get; set; }
        public string Amphurname { get; set; }
        public string Changwatshortname { get; set; }
        public string Provinceid { get; set; }
        public string Cityid { get; set; }
        public string Status { get; set; }
    }
}