// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Changwat
    {
        public string Changwatshortname { get; set; }
        public string Changwatname { get; set; }
        public string Changwattrnsp { get; set; }
        public string Branchid { get; set; }
        public string Provinceid { get; set; }
    }
}