// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosAccident
    {
        public string AccNo { get; set; }
        public DateTime? DateRec { get; set; }
        public string TimeRec { get; set; }
        public DateTime? DateAcc { get; set; }
        public string TimeAcc { get; set; }
        public string AccPlace { get; set; }
        public string AccProv { get; set; }
        public string AccPolStn { get; set; }
        public string PolicePrefix { get; set; }
        public string PoliceFname { get; set; }
        public string PoliceLname { get; set; }
        public string InfFname { get; set; }
        public string InfLname { get; set; }
        public string InfAdd { get; set; }
        public string InfTelNo { get; set; }
        public string AccType { get; set; }
        public string AccTypeCase { get; set; }
        public short? AccTypeParty { get; set; }
        public short? AccTypeVictim { get; set; }
        public string AccNature { get; set; }
        public string PoliceDoc { get; set; }
        public string PoliceDocNo { get; set; }
        public DateTime? PoliceDocDate { get; set; }
        public string SumCase { get; set; }
        public string ReceiveBy { get; set; }
        public string Status { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string SendStatus { get; set; }
        public DateTime? SendDate { get; set; }
        public string HosAccNo { get; set; }
        public string InformNo { get; set; }
        public string HqStatus { get; set; }
        public string HospitalId { get; set; }
        public string ClaimNo { get; set; }
        public string CutData { get; set; }
        public DateTime? Regisdate { get; set; }
        public string AccDist { get; set; }
        public string AccSubDist { get; set; }
        public string InfAddSubDist { get; set; }
        public string InfAddDist { get; set; }
        public string InfAddProv { get; set; }
        public string Survey { get; set; }
        public string SurveyComment { get; set; }
        public string Claim30Day { get; set; }
        public string ChangeCarLicense { get; set; }
        public string ClaimDuplicate { get; set; }
        public string ChangeVictim { get; set; }
        public string ChangeSumCase { get; set; }
        public string ChangeAccident { get; set; }
        public string OtherCase { get; set; }
        public DateTime? SurveyDate { get; set; }
        public DateTime? SurveyEntryDate { get; set; }
        public string SurveyEntryBy { get; set; }
        public string GetRecordStatus { get; set; }
        public DateTime? GetRecordDate { get; set; }
        public DateTime? GetEditRecordDate { get; set; }
        public DateTime? CanCelDate { get; set; }
        public string SentHi01 { get; set; }
        public DateTime? SentHi01Date { get; set; }
        public string SentHi04 { get; set; }
        public DateTime? SentHi04Date { get; set; }
        public string UserId { get; set; }
        public string BranchId { get; set; }
        public string AccNoOld { get; set; }
        public string NewStatus { get; set; }
        public string InputBy { get; set; }
        public string FalseInform { get; set; }
        public string Surveyed { get; set; }
        public string OutSurveyed { get; set; }
        public string GetRecordBy { get; set; }
        public string UserIp { get; set; }
        public string SurveyPlaceTsc { get; set; }
        public string SurveyPlaceEacc { get; set; }
        public string SurveyPlacePol { get; set; }
        public string TypeSurveyOPolice { get; set; }
        public string TypeSurveyOHos { get; set; }
        public string TypeSurveyOAcc { get; set; }
        public string TypeSurveyOOther { get; set; }
        public string TextSurveyOut { get; set; }
        public string TypeCase { get; set; }
        public string TypeCaseSel { get; set; }
        public string TextTypeCase { get; set; }
        public string CaseEnd { get; set; }
        public string InsureCover { get; set; }
        public string NotCoverCase { get; set; }
        public string FundClaimNo { get; set; }
        public string AccNoEr { get; set; }
        public string InputByFirst { get; set; }
        public string AddCarLate { get; set; }
        public string SameVicOwn { get; set; }
        public string RepeatAccNo { get; set; }
        public string AccNoEacc { get; set; }
        public short? DiffDay { get; set; }
        public DateTime? DiffDayProcess { get; set; }
        public string AccNoEaccMore { get; set; }
        public string AccNoIndicateType { get; set; }
    }
}