// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosAccidentCheckTypes
    {
        public int TypeId { get; set; }
        public int? ParentTypeId { get; set; }
        public string TypeName { get; set; }
        public bool? IsActive { get; set; }
    }
}