// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosApproval
    {
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public int AppNo { get; set; }
        public DateTime? DateCreate { get; set; }
        public DateTime? RegDate { get; set; }
        public string RegType { get; set; }
        public double? MedicineMoney { get; set; }
        public double? PlasticMoney { get; set; }
        public double? ServiceMoney { get; set; }
        public double? RoomMoney { get; set; }
        public double? VeihcleMoney { get; set; }
        public double? SumMoney { get; set; }
        public string Pt4id { get; set; }
        public string InvoiceDoc { get; set; }
        public string SendStatus { get; set; }
        public DateTime? SendDate { get; set; }
        public int? TypePaid { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string InFormNo { get; set; }
        public string Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public DateTime? ConfirmedDate { get; set; }
        public string ClaimNo { get; set; }
        public short? VictimNoClaim { get; set; }
        public short? RegNoClaim { get; set; }
        public string DocumentNo { get; set; }
        public string CanPaid { get; set; }
        public double? CanPaidMoney { get; set; }
        public string ReferId { get; set; }
        public string HosIdRefer { get; set; }
        public string SentHi04 { get; set; }
        public DateTime? SendHi04Date { get; set; }
        public string Kcl008no { get; set; }
        public string ChequeNo { get; set; }
        public string BankId { get; set; }
        public string BankBranchId { get; set; }
        public DateTime? ChequeDate { get; set; }
        public string Pvno { get; set; }
        public DateTime? Iocdate { get; set; }
        public string BranchId { get; set; }
        public DateTime? GetRecordDate { get; set; }
        public string GetRecordStatus { get; set; }
        public string UserId { get; set; }
        public string PayMore { get; set; }
        public double? CureMoney { get; set; }
        /// <summary>
        /// 0
        /// </summary>
        public double? DeadMoney { get; set; }
        /// <summary>
        /// 0
        /// </summary>
        public double? HygieneMoney { get; set; }
        /// <summary>
        /// 0
        /// </summary>
        public double? CrippledMoney { get; set; }
        public string BlindCrippled { get; set; }
        public string UnHearCrippled { get; set; }
        public string DeafCrippled { get; set; }
        public string LostSexualCrippled { get; set; }
        public string LostOrganCrippled { get; set; }
        public string LostMindCrippled { get; set; }
        public string CrippledPermanent { get; set; }
        public string OtherCrippled { get; set; }
        public string CrippledComment { get; set; }
        public string RevPrefix { get; set; }
        public string RevFname { get; set; }
        public string RevLname { get; set; }
        public string RevRelate { get; set; }
        public string RecPrefix { get; set; }
        public string RecFname { get; set; }
        public string RecLname { get; set; }
        public string RecRelate { get; set; }
        public string RecSocNo { get; set; }
        public string PayMoreClaimNo { get; set; }
        public string InputBy { get; set; }
        /// <summary>
        /// รพ.ที่รับรักษา
        /// </summary>
        public string HospitalTreat { get; set; }
        public string ClaimTo { get; set; }
        public string ReceivingDoc { get; set; }
        public string InvoiceNo { get; set; }
        public int? InvoiceAmount { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public string PoliceDoc { get; set; }
        public string SocNoDoc { get; set; }
        public string ForeignDoc { get; set; }
        public string Passport { get; set; }
        public string HouseDoc { get; set; }
        public string CarBookDoc { get; set; }
        public string PolicyDoc { get; set; }
        public string OtherDoc { get; set; }
        public string OtherDocComment { get; set; }
        public string RevAddress { get; set; }
        public string RevsubDistrict { get; set; }
        public string RevDistrict { get; set; }
        public string RevProvince { get; set; }
        public string IdCardType { get; set; }
        public string IdCardNo { get; set; }
        public string FundClaimNo { get; set; }
        public int? FundVictimNo { get; set; }
        public int? FundRegNo { get; set; }
        public string DocumentNoEr { get; set; }
        /// <summary>
        /// วันที่นัดจ่าย/ธเกิง 02-06-51
        /// </summary>
        public DateTime? DueDate { get; set; }
        /// <summary>
        /// รับเรื่องโดย/ธเกิง 02-06-51
        /// </summary>
        public string AcceptBy { get; set; }
        /// <summary>
        /// วันที่รับเรื่อง/ธเกิง 02-06-51
        /// </summary>
        public DateTime? AcceptDate { get; set; }
        public string DenyComment { get; set; }
        public string ClaimRegisComment { get; set; }
        public string CanCelStatus { get; set; }
        public DateTime? Takendate { get; set; }
        public string TakenTime { get; set; }
        public DateTime? Dispensedate { get; set; }
        public string Dispensetime { get; set; }
        public decimal? CompensateMoney { get; set; }
        public short? CompensateDay { get; set; }
        public string CaccNo { get; set; }
        public short? CvictimNo { get; set; }
        public short? CrunNo { get; set; }
        public string PaidType { get; set; }
        public short? SurplusDay { get; set; }
        public string TypeSurplus { get; set; }
        public string InvoiceType { get; set; }
        public string RecInsId { get; set; }
        public string Accept { get; set; }
        public string DocumentComplete { get; set; }
        public string Emspayment { get; set; }
        public string MCardType { get; set; }
        public string MCardTypeOther { get; set; }
        public DateTime? RecBirthDate { get; set; }
        public string RecTelephone { get; set; }
        public string RecCurrentAddress { get; set; }
        public string RecCurrentProvince { get; set; }
        public string RecCurrentDistrict { get; set; }
        public string RecCurrentSubDistrict { get; set; }
        public string RecHouseAddress { get; set; }
        public string RecHouseProvince { get; set; }
        public string RecHouseDistrict { get; set; }
        public string RecHouseSubDistrict { get; set; }
        public string SameVictimAddress { get; set; }
        public string SameHouseVictimAddress { get; set; }
        public short? RecNationalityId { get; set; }
        public string VictimType { get; set; }
        /// <summary>
        /// สถานะยืนยันKCL014
        /// </summary>
        public string Kcl014Status { get; set; }
        /// <summary>
        /// หมายเหตุยืนยันKCL014
        /// </summary>
        public string Kcl014Comment { get; set; }
        /// <summary>
        /// วันที่ยืนยันkcl014
        /// </summary>
        public DateTime? Kcl014Date { get; set; }
        /// <summary>
        /// ผู้ยืนยันkcl014
        /// </summary>
        public string Kcl014By { get; set; }
    }
}