// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosAccidentCheck
    {
        public string AccNo { get; set; }
        /// <summary>
        /// จำนวนรอบที่ส่งคำร้อง
        /// </summary>
        public int StateNo { get; set; }
        /// <summary>
        /// สถานะคำร้อง
        /// </summary>
        public int? Status { get; set; }
        public DateTime? InsertDate { get; set; }
        /// <summary>
        /// ตรวสอบรูปภาพสภาพแวดล้อมที่เกิดเหตุ
        /// </summary>
        public string AccNatureImgCheckType { get; set; }
        public string AccNutureImageCheckComment { get; set; }
        /// <summary>
        /// ตรวจสอบรถที่เกิดเหตุ
        /// </summary>
        public string AccCarImgCheckType { get; set; }
        public string AccCarImgCheckComment { get; set; }
        /// <summary>
        /// ตรวจสอบรูปภาพอาการบาดเจ็บ
        /// </summary>
        public string AccVictimImgCheckType { get; set; }
        public string AccVictimImgCheckComment { get; set; }
        public string RecordBy { get; set; }
        public string Ip { get; set; }
        public string BranchId { get; set; }
    }
}