// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosCarAccident
    {
        public string AccNo { get; set; }
        public short TpNo { get; set; }
        public string InsId { get; set; }
        public string PolNo { get; set; }
        public DateTime? EffDate { get; set; }
        public DateTime? ExpDate { get; set; }
        public string InsPrefix { get; set; }
        public string InsFname { get; set; }
        public string InsLname { get; set; }
        public string TypeInsurerC { get; set; }
        public string TypeInsurerB { get; set; }
        public string StickerNo { get; set; }
        public string CushiNo { get; set; }
        public short? EngineSize { get; set; }
        public string CarBand { get; set; }
        public string CarLicense { get; set; }
        public string CarProv { get; set; }
        public string CarColor { get; set; }
        public string DrvPrefix { get; set; }
        public string DrvFname { get; set; }
        public string DrvLname { get; set; }
        public string DrvAdd { get; set; }
        public string DrvAddProv { get; set; }
        public string DrvTelNo { get; set; }
        public string CarType { get; set; }
        public string CarLicenseDoc { get; set; }
        public string PolStickerDoc { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string SendStatus { get; set; }
        public DateTime? SendDate { get; set; }
        public string ClaimNo { get; set; }
        public short? CarNoClaim { get; set; }
        public string DrvAddDist { get; set; }
        public string DrvAddSubDist { get; set; }
        public string HomeId { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string SentHi01 { get; set; }
        public DateTime? SentHi01Date { get; set; }
        public string SentHi04 { get; set; }
        public DateTime? SentHi04Date { get; set; }
        public string ClaimNoOfIoc { get; set; }
        public DateTime? RvpRegisClaimDate { get; set; }
        public DateTime? Regisdate { get; set; }
        public string StatusCanCelCar { get; set; }
        public DateTime? CancelDate { get; set; }
        public string SearchStatus { get; set; }
        public string FoundPolicyNo { get; set; }
        public string FoundStickerNo { get; set; }
        public DateTime? FoundEffDate { get; set; }
        public DateTime? FoundExpDate { get; set; }
        public string FoundInsId { get; set; }
        public string InputBy { get; set; }
        public string Accnodup { get; set; }
        public string BranchId { get; set; }
        public short? CarNoDup { get; set; }
        public string Comment { get; set; }
        public string FirstName { get; set; }
        public string FoundCarLicense { get; set; }
        public string FoundCarProv { get; set; }
        public string FoundChassisNo { get; set; }
        public DateTime? GetRecordDate { get; set; }
        public string GetRecordStatus { get; set; }
        public string SureName { get; set; }
        public string TitleName { get; set; }
        public string UserId { get; set; }
        public short? FoundEnginesize { get; set; }
        public string FoundCarType { get; set; }
        public string FoundCarBrand { get; set; }
        /// <summary>
        /// คำนำหน้าชื่อเจ้าของรถ
        /// </summary>
        public string CarOwnerPrefix { get; set; }
        /// <summary>
        /// ชื่อเจ้าของรถ
        /// </summary>
        public string CarOwnerFname { get; set; }
        /// <summary>
        /// นามสกุลเจ้าของรถ
        /// 
        /// </summary>
        public string CarOwnerLname { get; set; }
        public string CarOwnerNo { get; set; }
        public string CarOwnerSoi { get; set; }
        public string CarOwnerRoad { get; set; }
        public string CarOwnerMoo { get; set; }
        public string CarOwnerSubDistrict { get; set; }
        public string CarOwnerDistrict { get; set; }
        public string CarOwnerProvince { get; set; }
        public string CarOwnerZipCode { get; set; }
        public string CarOwnerTelNo { get; set; }
        public string FundClaimNo { get; set; }
        public int? FundCarNo { get; set; }
        public string ChassisNoByInput { get; set; }
        public string ChassisNoBySearch { get; set; }
        public string InputByFirst { get; set; }
        public string OwnerPrefix { get; set; }
        public string OwnerFname { get; set; }
        public string OwnerLname { get; set; }
        public string OwnerHomId { get; set; }
        public string OwnerMoo { get; set; }
        public string OwnerSoi { get; set; }
        public string OwnerRoad { get; set; }
        public string OwnerTumbol { get; set; }
        public string OwnerAmphur { get; set; }
        public string OwnerChangwat { get; set; }
        public string OwnerZipcode { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerTelHome { get; set; }
        public string OwnerTelOffice { get; set; }
        public string StatusNotCar { get; set; }
        public string KeyCutCarlicense { get; set; }
        public string KeyCutPolno { get; set; }
        public string KeyCutCushino { get; set; }
        public string CutFoundChassisNo { get; set; }
        public string CutFoundPolicyNo { get; set; }
        public string CutFoundCarlicense { get; set; }
        public string AccnoSurplus { get; set; }
        public short? TpnoSurplus { get; set; }
        /// <summary>
        /// ยืนยันความคู้มครองส่วนเกิน
        /// </summary>
        public string ConfirmBy { get; set; }
        /// <summary>
        /// วันที่ยืนยันรถ(ส่วนเกิน)
        /// </summary>
        public DateTime? ConfirmDate { get; set; }
        public string ConfirmIp { get; set; }
        public string TypeMotor { get; set; }
        public string FoundTypeMotor { get; set; }
        public string NeedToBillOic { get; set; }
        public string SumcaseW { get; set; }
    }
}