// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Hospital
    {
        public string Hospitalid { get; set; }
        public string Hospitalname { get; set; }
        public string Changwatshortname { get; set; }
        public short? Hospitalduedate { get; set; }
        public string Hospitaltradename { get; set; }
        public string Hospitalestablishid { get; set; }
        public string Contract { get; set; }
        public string Mediaclearing { get; set; }
        public string Bankcode { get; set; }
        public string Accountno { get; set; }
        public string Accountname { get; set; }
        public string Eclaim { get; set; }
        public string Ehi { get; set; }
        public string Email { get; set; }
        public string TelephoneNo { get; set; }
        public string Mobileno { get; set; }
        public string FaxNo { get; set; }
        public string TaxNo { get; set; }
        public string ContactName { get; set; }
        public string BranchId { get; set; }
        public string AddressNo { get; set; }
        public string AddressMoo { get; set; }
        public string AddressSoi { get; set; }
        public string AddressRoad { get; set; }
        public string AddressDistrict { get; set; }
        public string AddressCity { get; set; }
        public string AddressProvince { get; set; }
        public string ZipCode { get; set; }
        public string HosType { get; set; }
        public string Active { get; set; }
        public string InputAccountNoBy { get; set; }
        public DateTime? InputAccountNoDate { get; set; }
        public string ConfirmedAccountNoBy { get; set; }
        public DateTime? ConfirmedAccountNodate { get; set; }
        public string AgentId { get; set; }
        public int? PeriodType { get; set; }
        public string Sapid { get; set; }
        public string Inputby { get; set; }
        public DateTime? Inputdate { get; set; }
        public string Hosprefix { get; set; }
        public string Oicprov { get; set; }
        public string IsPa { get; set; }
        public string InvoiceType { get; set; }
        public short? BookId { get; set; }
    }
}