// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosPt4
    {
        public string Pt4id { get; set; }
        public DateTime? Pt4date { get; set; }
        public string SendStatus { get; set; }
        public DateTime? SendDate { get; set; }
        public string UserCreate { get; set; }
        public DateTime? GetRecordDate { get; set; }
        public string GetRecordStatus { get; set; }
        public string DocumentType { get; set; }
    }
}