// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class HosVicTimAccident
    {
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public string Prefix { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Sex { get; set; }
        public short? Age { get; set; }
        public string DrvSocNo { get; set; }
        public string HomeId { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string Tumbol { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
        public string TelNo { get; set; }
        public string SendBy { get; set; }
        public string SendName { get; set; }
        public double? EstimateMoney { get; set; }
        public DateTime? HosRecDate { get; set; }
        public string HosRecTime { get; set; }
        public string VicTimIs { get; set; }
        public string VictimType { get; set; }
        public short? CarNo { get; set; }
        public string VicTimId { get; set; }
        public string HosRoom { get; set; }
        public string Broken { get; set; }
        public string DetailBroken { get; set; }
        public int? AssessKeepDay { get; set; }
        public double? AssessKeepMoney { get; set; }
        public string DocName { get; set; }
        public string DocId { get; set; }
        public string Consider { get; set; }
        public int? ChkHi01 { get; set; }
        public string SocNoDoc { get; set; }
        public string HouseDoc { get; set; }
        public string DeadDoc { get; set; }
        public string RepreDoc { get; set; }
        public string DoctorDoc { get; set; }
        public string Pt4doc { get; set; }
        public string DrvLicenseDoc { get; set; }
        public string SendStatus { get; set; }
        public DateTime? LastUpdate { get; set; }
        public DateTime? SendDate { get; set; }
        public string ClaimNo { get; set; }
        public short? VictimNoClaim { get; set; }
        public string Confirmed { get; set; }
        public DateTime? ConfirmedDate { get; set; }
        public string ConfirmedBy { get; set; }
        public string CaseNot { get; set; }
        public string ChangwatRefer { get; set; }
        public string HospitalIdRefer { get; set; }
        public string SentHi01 { get; set; }
        public DateTime? SentHi01Date { get; set; }
        public string SentHi04 { get; set; }
        public DateTime? SentHi04Date { get; set; }
        public DateTime? Regisdate { get; set; }
        public string StatusCanCelVtm { get; set; }
        public DateTime? CanCelDate { get; set; }
        public string InputBy { get; set; }
        public string AccNoDup { get; set; }
        public string BranchId { get; set; }
        public DateTime? GetRecordDate { get; set; }
        public string GetRecordStatus { get; set; }
        public string UserId { get; set; }
        public int? VictimNoDup { get; set; }
        /// <summary>
        /// รพ.ที่รับรักษา
        /// </summary>
        public string HospitalIdTreat { get; set; }
        public string VCf014 { get; set; }
        /// <summary>
        /// อาชีพ
        /// </summary>
        public string Occupation { get; set; }
        /// <summary>
        /// บ.ประกันจ่าย/ไม่จ่ายบต
        /// </summary>
        public string InsurerPaid { get; set; }
        /// <summary>
        /// จำนวนเงินที่จ่ายแล้ว
        /// </summary>
        public double? InsurerPaidAmount { get; set; }
        /// <summary>
        /// วันที่บ.ประกันจ่าย บต.
        /// </summary>
        public DateTime? InsurerDate { get; set; }
        public string GetMoneyCarOwner { get; set; }
        public double? MoneyCarOwner { get; set; }
        public string HospitalAuthorize { get; set; }
        public string HospitalAuthorizeId { get; set; }
        public double? MoneyHospital { get; set; }
        public string FundClaimNo { get; set; }
        public int? FundVictimNo { get; set; }
        public string InputByFirst { get; set; }
        public DateTime? ConfirmedDate2 { get; set; }
        public string ConfirmedBy2 { get; set; }
        public string CoverCase { get; set; }
        /// <summary>
        /// ประเภทบัตร
        /// </summary>
        public string TypeCard { get; set; }
        /// <summary>
        /// พฤติกรรมความเสี่ยง หมวกนิภัย
        /// </summary>
        public string RiskAlgohol { get; set; }
        /// <summary>
        /// พฤติกรรมความเสี่ยง แอลกอฮอล์  
        /// </summary>
        public string RiskMobile { get; set; }
        /// <summary>
        /// พฤติกรรมความเสี่ยง โทรศัพท์เคลื่อนที่   
        /// </summary>
        public string RiskSafetyBelt { get; set; }
        /// <summary>
        /// พฤติกรรมความเสี่ยง  เข็มขัดนิรภัย  
        /// </summary>
        public string RiskHelmet { get; set; }
        /// <summary>
        /// พฤติกรรมความเสี่ยง values 1 = มี,ใช้  ,2 = ไม่มี, ไม่ใช้     ,3 = ไม่ทราบ
        /// </summary>
        public string RiskValueAlgohol { get; set; }
        public string RiskValueMobile { get; set; }
        public string RiskValueSafetyBelt { get; set; }
        public string RiskValueHelmet { get; set; }
        public string InsureType { get; set; }
        public string NotCoverCase { get; set; }
        /// <summary>
        /// วันที่เสียชีวิต
        /// </summary>
        public DateTime? DeadDate { get; set; }
        /// <summary>
        /// อาชีพ
        /// </summary>
        public byte? CareerId { get; set; }
        public string CareerOther { get; set; }
        public string School { get; set; }
        public string DeadNo { get; set; }
        public DateTime? BirthDate { get; set; }
        public short? NationalityId { get; set; }
        public string CardTypeOther { get; set; }
        public string LockWatchList { get; set; }
        public string An { get; set; }
        public string CarLiCenseConfirm { get; set; }
        public string CarLicenseCarProvConfirm { get; set; }
        public string PolicyNoConfirm { get; set; }
        public short? CarNoConfirm { get; set; }
        public string PaCheckPolicy { get; set; }
        public string PaCheckInsure { get; set; }
        public string PaPolicyNo { get; set; }
        public short? DisableId { get; set; }
        public string AlterHomeId { get; set; }
        public string AlterMoo { get; set; }
        public string AlterSoi { get; set; }
        public string AlterRoad { get; set; }
        public string AlterTumbol { get; set; }
        public string AlterDistrict { get; set; }
        public string AlterProvince { get; set; }
        /// <summary>
        /// เลขเคลมของบริษัทประกันภัยยืนยันKCL014
        /// </summary>
        public string Kcl014ClaimNo { get; set; }
    }
}