// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Invoicedt
    {
        public long IdInvdt { get; set; }
        public int? Listno { get; set; }
        public long Treatid { get; set; }
        public double? Price { get; set; }
        public string InvdtComment { get; set; }
        public string Recordby { get; set; }
        public DateTime? Recorddate { get; set; }
        public string Ip { get; set; }
    }
}