// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Mcwounded
    {
        public short WoundedId { get; set; }
        public string WoundedName { get; set; }
        public string GroupId { get; set; }
        public string Organ { get; set; }
        public string Status { get; set; }
        public string OrderBy { get; set; }
        public int? Daybed { get; set; }
        public string Ioc { get; set; }
        public string RecordBy { get; set; }
        public DateTime? RecordDate { get; set; }
        public string RecordIp { get; set; }
    }
}