// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Particulars
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Pos { get; set; }
        public string DoiCode { get; set; }
        public string Level { get; set; }
        public int? Topic { get; set; }
    }
}