// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Prefix
    {
        public string Titlename { get; set; }
        public string Titledesc { get; set; }
        public string Titlepolice { get; set; }
        public string Sex { get; set; }
        /// <summary>
        /// ลำดับการแสดง
        /// </summary>
        public short? Seq { get; set; }
    }
}