// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DataAccess.EFCore.RvpOfficeModels;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class RvpofficeContext
    {

        [DbFunction("fnGenerateAccNo", "dbo")]
        public static string fnGenerateAccNo(string Branchid)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
