// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpOfficeModels
{
    public partial class Tumbol
    {
        public string Tumbolid { get; set; }
        public string Tumbolname { get; set; }
        public string Amphurid { get; set; }
        public string Zipcode { get; set; }
        public string Changwatshortname { get; set; }
        public string Provinceid { get; set; }
        public string Cityid { get; set; }
        public string Districtid { get; set; }
        public string Tumbolengname { get; set; }
        public string Status { get; set; }
    }
}