// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace DataAccess.EFCore.Models
{
    public partial class RvpAccidentContext : DbContext
    {
        public RvpAccidentContext()
        {
        }

        public RvpAccidentContext(DbContextOptions<RvpAccidentContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TbAccidentMasterLine> TbAccidentMasterLine { get; set; }
        public virtual DbSet<TbAccidentMasterLineCar> TbAccidentMasterLineCar { get; set; }
        public virtual DbSet<TbAccidentMasterLineVictim> TbAccidentMasterLineVictim { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Thai_CI_AS");

            modelBuilder.Entity<TbAccidentMasterLine>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLine");

                entity.Property(e => e.EaAccDate)
                    .HasPrecision(3)
                    .HasColumnName("ea_AccDate");

                entity.Property(e => e.EaAccDistrict)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccDistrict");

                entity.Property(e => e.EaAccLatLong)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccLatLong");

                entity.Property(e => e.EaAccLatitude).HasColumnName("ea_AccLatitude");

                entity.Property(e => e.EaAccLongitude).HasColumnName("ea_AccLongitude");

                entity.Property(e => e.EaAccNature)
                    .HasMaxLength(2000)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccNature");

                entity.Property(e => e.EaAccNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccNo");

                entity.Property(e => e.EaAccNoEclaim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccNoEclaim");

                entity.Property(e => e.EaAccPlace)
                    .HasMaxLength(2000)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccPlace");

                entity.Property(e => e.EaAccPrefecture)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccPrefecture");

                entity.Property(e => e.EaAccProvince)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccProvince");

                entity.Property(e => e.EaAccTime)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccTime");

                entity.Property(e => e.EaAccTypeCase)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccTypeCase");

                entity.Property(e => e.EaAccTypeGroup)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccTypeGroup");

                entity.Property(e => e.EaAccZoom).HasColumnName("ea_AccZoom");

                entity.Property(e => e.EaBranchId)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_BranchID");

                entity.Property(e => e.EaInformDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_InformDate");

                entity.Property(e => e.EaInformTime)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_InformTime");

                entity.Property(e => e.EaInputChannel)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_InputChannel");

                entity.Property(e => e.EaInsertDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_InsertDate");

                entity.Property(e => e.EaInsertIp)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_InsertIP");

                entity.Property(e => e.EaLastUpdate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_LastUpdate");

                entity.Property(e => e.EaStatus).HasColumnName("ea_Status");

                entity.Property(e => e.EaStatusCancelBy)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_StatusCancelBy");

                entity.Property(e => e.EaStatusCancelDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_StatusCancelDate");

                entity.Property(e => e.EaStatusCancelIp)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_StatusCancelIP");

                entity.Property(e => e.EaTmpId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_TmpID");

                entity.Property(e => e.EaUpdateBy)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_UpdateBy");

                entity.Property(e => e.EaUpdateIp)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_UpdateIP");

                entity.Property(e => e.EaUserId)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_UserID");

                entity.Property(e => e.Kycno).HasColumnName("KYCNo");

                entity.Property(e => e.TokenId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TokenID");
            });

            modelBuilder.Entity<TbAccidentMasterLineCar>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLineCar");

                entity.Property(e => e.EaAccNo)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_AccNo");

                entity.Property(e => e.EaCarBand)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarBand");

                entity.Property(e => e.EaCarCancelDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CarCancelDate");

                entity.Property(e => e.EaCarCancelStatus).HasColumnName("ea_CarCancelStatus");

                entity.Property(e => e.EaCarColor)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarColor");

                entity.Property(e => e.EaCarCushiNo)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarCushiNo");

                entity.Property(e => e.EaCarFirstName)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFirstName");

                entity.Property(e => e.EaCarFoundCarBrand)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundCarBrand");

                entity.Property(e => e.EaCarFoundCarLicense)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundCarLicense");

                entity.Property(e => e.EaCarFoundCarProv)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundCarProv");

                entity.Property(e => e.EaCarFoundCarType)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundCarType");

                entity.Property(e => e.EaCarFoundChassisNo)
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundChassisNo");

                entity.Property(e => e.EaCarFoundEffDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CarFoundEffDate");

                entity.Property(e => e.EaCarFoundEnginesize).HasColumnName("ea_CarFoundEnginesize");

                entity.Property(e => e.EaCarFoundExpDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CarFoundExpDate");

                entity.Property(e => e.EaCarFoundInsId)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundInsId");

                entity.Property(e => e.EaCarFoundPolicyNo)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarFoundPolicyNo");

                entity.Property(e => e.EaCarGroup)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarGroup");

                entity.Property(e => e.EaCarInsertBy)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarInsertBy");

                entity.Property(e => e.EaCarInsertDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CarInsertDate");

                entity.Property(e => e.EaCarInsertIp)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarInsertIP");

                entity.Property(e => e.EaCarLastUpdate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CarLastUpdate");

                entity.Property(e => e.EaCarLicense)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarLicense");

                entity.Property(e => e.EaCarModel)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarModel");

                entity.Property(e => e.EaCarNo).HasColumnName("ea_CarNo");

                entity.Property(e => e.EaCarPolNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarPolNo");

                entity.Property(e => e.EaCarProv)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarProv");

                entity.Property(e => e.EaCarSearchStatus)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarSearchStatus")
                    .IsFixedLength(true);

                entity.Property(e => e.EaCarSurName)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarSurName");

                entity.Property(e => e.EaCarTitleName)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarTitleName");

                entity.Property(e => e.EaCarType)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarType");

                entity.Property(e => e.EaCarUpdateBy)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarUpdateBy");

                entity.Property(e => e.EaCarUpdateIp)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_CarUpdateIP");

                entity.Property(e => e.EaStatusNotCar)
                    .HasMaxLength(2)
                    .HasColumnName("ea_StatusNotCar");

                entity.Property(e => e.EaStatusNotCarInt)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ea_StatusNotCarInt");

                entity.Property(e => e.EaTmpId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_TmpID");

                entity.Property(e => e.EaUserId)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_UserID");

                entity.Property(e => e.Kycno).HasColumnName("KYCNO");

                entity.Property(e => e.TokenId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TokenID");
            });

            modelBuilder.Entity<TbAccidentMasterLineVictim>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLineVictim");

                entity.Property(e => e.EaAccno)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ea_Accno");

                entity.Property(e => e.EaAddressVictim)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("ea_AddressVictim");

                entity.Property(e => e.EaAgeVictim).HasColumnName("ea_AgeVictim");

                entity.Property(e => e.EaAmphurVictim)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_AmphurVictim");

                entity.Property(e => e.EaBirthday)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_Birthday");

                entity.Property(e => e.EaBrokenDetail)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_BrokenDetail");

                entity.Property(e => e.EaBrokenVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_BrokenVictim");

                entity.Property(e => e.EaCancelDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_CancelDate");

                entity.Property(e => e.EaCarNo).HasColumnName("ea_CarNo");

                entity.Property(e => e.EaChangwatVictim)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_ChangwatVictim");

                entity.Property(e => e.EaConfirmed)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ea_confirmed");

                entity.Property(e => e.EaConfirmedby)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_confirmedby");

                entity.Property(e => e.EaConfirmeddate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_confirmeddate");

                entity.Property(e => e.EaCountryVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_CountryVictim");

                entity.Property(e => e.EaDateDead)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_DateDead");

                entity.Property(e => e.EaDeadNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_DeadNo");

                entity.Property(e => e.EaFnameVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_FnameVictim");

                entity.Property(e => e.EaForeign).HasColumnName("ea_Foreign");

                entity.Property(e => e.EaHosRecDateTime)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_HosRecDateTime");

                entity.Property(e => e.EaIdCardType)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_IdCardType");

                entity.Property(e => e.EaIdCardVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_IdCardVictim");

                entity.Property(e => e.EaInsertBy)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_InsertBy");

                entity.Property(e => e.EaInsertDate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_InsertDate");

                entity.Property(e => e.EaInsertIp)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_InsertIP");

                entity.Property(e => e.EaLastUpdate)
                    .HasColumnType("datetime")
                    .HasColumnName("ea_LastUpdate");

                entity.Property(e => e.EaLnameVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_LnameVictim");

                entity.Property(e => e.EaMooVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_MooVictim");

                entity.Property(e => e.EaNationalityId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_NationalityId");

                entity.Property(e => e.EaPhoneNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_PhoneNumber");

                entity.Property(e => e.EaPrefixVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_PrefixVictim");

                entity.Property(e => e.EaReferChangwat)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_ReferChangwat");

                entity.Property(e => e.EaReferCountry)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_ReferCountry");

                entity.Property(e => e.EaReferHospital)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("ea_ReferHospital");

                entity.Property(e => e.EaRoadVictim)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ea_RoadVictim");

                entity.Property(e => e.EaSexVictim)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ea_SexVictim");

                entity.Property(e => e.EaSoiVictim)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_SoiVictim");

                entity.Property(e => e.EaStatusCancel).HasColumnName("ea_StatusCancel");

                entity.Property(e => e.EaStatusVictim)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_StatusVictim");

                entity.Property(e => e.EaTmpId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_TmpID");

                entity.Property(e => e.EaTumbolVictim)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ea_TumbolVictim");

                entity.Property(e => e.EaUpdateBy)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_UpdateBy");

                entity.Property(e => e.EaUpdateIp)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ea_UpdateIP");

                entity.Property(e => e.EaUserId)
                    .HasMaxLength(36)
                    .IsUnicode(false)
                    .HasColumnName("ea_UserID");

                entity.Property(e => e.EaVictimId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_VictimId");

                entity.Property(e => e.EaVictimNo).HasColumnName("ea_VictimNo");

                entity.Property(e => e.EaVictimType)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ea_VictimType");

                entity.Property(e => e.Kycno).HasColumnName("KYCNO");

                entity.Property(e => e.TokenId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TokenID");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}