// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.EFCore.Models
{
    public partial class TbAccidentMasterLineVictim
    {
        public string EaTmpId { get; set; }
        public string EaAccno { get; set; }
        public int? EaCarNo { get; set; }
        public int? EaVictimNo { get; set; }
        public string EaPrefixVictim { get; set; }
        public string EaFnameVictim { get; set; }
        public string EaLnameVictim { get; set; }
        public string EaSexVictim { get; set; }
        public DateTime? EaBirthday { get; set; }
        public short? EaAgeVictim { get; set; }
        public string EaNationalityId { get; set; }
        public string EaIdCardType { get; set; }
        public string EaIdCardVictim { get; set; }
        public string EaPhoneNumber { get; set; }
        public string EaAddressVictim { get; set; }
        public string EaMooVictim { get; set; }
        public string EaSoiVictim { get; set; }
        public string EaRoadVictim { get; set; }
        public string EaChangwatVictim { get; set; }
        public string EaAmphurVictim { get; set; }
        public string EaTumbolVictim { get; set; }
        public string EaStatusVictim { get; set; }
        public string EaVictimType { get; set; }
        public string EaBrokenVictim { get; set; }
        public string EaBrokenDetail { get; set; }
        public string EaUserId { get; set; }
        public DateTime EaInsertDate { get; set; }
        public string EaInsertBy { get; set; }
        public string EaInsertIp { get; set; }
        public bool? EaStatusCancel { get; set; }
        public DateTime? EaCancelDate { get; set; }
        public DateTime? EaLastUpdate { get; set; }
        public string EaUpdateBy { get; set; }
        public string EaUpdateIp { get; set; }
        public string EaReferChangwat { get; set; }
        public string EaReferHospital { get; set; }
        public string EaConfirmed { get; set; }
        public DateTime? EaConfirmeddate { get; set; }
        public string EaConfirmedby { get; set; }
        public bool? EaForeign { get; set; }
        public DateTime? EaDateDead { get; set; }
        public string EaDeadNo { get; set; }
        public string EaCountryVictim { get; set; }
        public string EaReferCountry { get; set; }
        public DateTime? EaHosRecDateTime { get; set; }
        public string EaVictimId { get; set; }
        public int? Kycno { get; set; }
        public string TokenId { get; set; }
    }
}