// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.EFCore.Models
{
    public partial class TbAccidentMasterLineCar
    {
        public string EaTmpId { get; set; }
        public string EaAccNo { get; set; }
        public short? EaCarNo { get; set; }
        public string EaCarType { get; set; }
        public string EaCarProv { get; set; }
        public string EaCarLicense { get; set; }
        public string EaCarCushiNo { get; set; }
        public string EaCarPolNo { get; set; }
        public string EaCarGroup { get; set; }
        public string EaCarBand { get; set; }
        public string EaCarModel { get; set; }
        public string EaCarColor { get; set; }
        public string EaCarTitleName { get; set; }
        public string EaCarFirstName { get; set; }
        public string EaCarSurName { get; set; }
        public string EaCarSearchStatus { get; set; }
        public string EaCarFoundCarType { get; set; }
        public string EaCarFoundPolicyNo { get; set; }
        public DateTime? EaCarFoundEffDate { get; set; }
        public DateTime? EaCarFoundExpDate { get; set; }
        public string EaCarFoundInsId { get; set; }
        public string EaCarFoundCarProv { get; set; }
        public string EaCarFoundCarLicense { get; set; }
        public string EaCarFoundChassisNo { get; set; }
        public short? EaCarFoundEnginesize { get; set; }
        public string EaCarFoundCarBrand { get; set; }
        public string EaUserId { get; set; }
        public DateTime? EaCarInsertDate { get; set; }
        public string EaCarInsertBy { get; set; }
        public string EaCarInsertIp { get; set; }
        public DateTime? EaCarLastUpdate { get; set; }
        public string EaCarUpdateBy { get; set; }
        public string EaCarUpdateIp { get; set; }
        public string EaStatusNotCar { get; set; }
        public string EaStatusNotCarInt { get; set; }
        public bool? EaCarCancelStatus { get; set; }
        public DateTime? EaCarCancelDate { get; set; }
        public int? Kycno { get; set; }
        public string TokenId { get; set; }
    }
}