// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.EFCore.Models
{
    public partial class TbAccidentMasterLine
    {
        public string EaTmpId { get; set; }
        public string EaAccNo { get; set; }
        public DateTime EaInsertDate { get; set; }
        public string EaInsertIp { get; set; }
        public DateTime? EaAccDate { get; set; }
        public string EaAccTime { get; set; }
        public DateTime? EaInformDate { get; set; }
        public string EaInformTime { get; set; }
        public string EaAccTypeGroup { get; set; }
        public string EaAccTypeCase { get; set; }
        public string EaAccProvince { get; set; }
        public string EaAccPrefecture { get; set; }
        public string EaAccDistrict { get; set; }
        public string EaAccPlace { get; set; }
        public string EaAccNature { get; set; }
        public string EaAccLatLong { get; set; }
        public double? EaAccLatitude { get; set; }
        public double? EaAccLongitude { get; set; }
        public byte? EaAccZoom { get; set; }
        public string EaBranchId { get; set; }
        public string EaUserId { get; set; }
        public string EaInputChannel { get; set; }
        public bool EaStatus { get; set; }
        public string EaUpdateBy { get; set; }
        public DateTime? EaLastUpdate { get; set; }
        public string EaUpdateIp { get; set; }
        public DateTime? EaStatusCancelDate { get; set; }
        public string EaStatusCancelBy { get; set; }
        public string EaStatusCancelIp { get; set; }
        public string EaAccNoEclaim { get; set; }
        public int? Kycno { get; set; }
        public string TokenId { get; set; }
    }
}