// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.HospitalModels
{
    public partial class Branch
    {
        /// <summary>
        /// รหัสสาขา
        /// </summary>
        public string Branchid { get; set; }
        public string Branchname { get; set; }
        public string Regionid { get; set; }
        public string Branchoff { get; set; }
        public string BankNo { get; set; }
        public string Ceo { get; set; }
        public string AcBranchId { get; set; }
        public string BranchPvr { get; set; }
        public string MainBranchId { get; set; }
        public string ChangwatShortName { get; set; }
        public string CanRegis { get; set; }
        public string BranchShortName { get; set; }
        public string TelNo { get; set; }
    }
}