// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.RvpSystemModels
{
    public partial class EDocDetail
    {
        public string SystemId { get; set; }
        public string TemplateId { get; set; }
        public string DocumentId { get; set; }
        public string RefId { get; set; }
        public int? RunningNo { get; set; }
        public string Paths { get; set; }
        public string StatusDoc { get; set; }
        public DateTime? CreateDate { get; set; }
        public string Createby { get; set; }
        public string CreateIp { get; set; }
        public DateTime? CancelDate { get; set; }
        public string Cancelby { get; set; }
        public string CancelIp { get; set; }
    }
}