// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.EFCore.AccidentModels
{
    public partial class RvpaccidentContext : DbContext
    {
        public RvpaccidentContext()
        {
        }

        public RvpaccidentContext(DbContextOptions<RvpaccidentContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TbAccidentMasterLine> TbAccidentMasterLine { get; set; }
        public virtual DbSet<TbAccidentMasterLineCar> TbAccidentMasterLineCar { get; set; }
        public virtual DbSet<TbAccidentMasterLineVictim> TbAccidentMasterLineVictim { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbAccidentMasterLine>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLine");

                entity.Property(e => e.EaAccDate)
                    .HasColumnName("ea_AccDate")
                    .HasColumnType("datetime2(3)");

                entity.Property(e => e.EaAccDistrict)
                    .HasColumnName("ea_AccDistrict")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccLatLong)
                    .HasColumnName("ea_AccLatLong")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccLatitude).HasColumnName("ea_AccLatitude");

                entity.Property(e => e.EaAccLongitude).HasColumnName("ea_AccLongitude");

                entity.Property(e => e.EaAccNature)
                    .HasColumnName("ea_AccNature")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccNo)
                    .HasColumnName("ea_AccNo")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccNoEclaim)
                    .HasColumnName("ea_AccNoEclaim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccPlace)
                    .HasColumnName("ea_AccPlace")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccPrefecture)
                    .HasColumnName("ea_AccPrefecture")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccProvince)
                    .HasColumnName("ea_AccProvince")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccTime)
                    .HasColumnName("ea_AccTime")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccTypeCase)
                    .HasColumnName("ea_AccTypeCase")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccTypeGroup)
                    .HasColumnName("ea_AccTypeGroup")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.EaAccZoom).HasColumnName("ea_AccZoom");

                entity.Property(e => e.EaBranchId)
                    .HasColumnName("ea_BranchID")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaInformDate)
                    .HasColumnName("ea_InformDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaInformTime)
                    .HasColumnName("ea_InformTime")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaInputChannel)
                    .HasColumnName("ea_InputChannel")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaInsertDate)
                    .HasColumnName("ea_InsertDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaInsertIp)
                    .HasColumnName("ea_InsertIP")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaLastUpdate)
                    .HasColumnName("ea_LastUpdate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaStatus).HasColumnName("ea_Status");

                entity.Property(e => e.EaStatusCancelBy)
                    .HasColumnName("ea_StatusCancelBy")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaStatusCancelDate)
                    .HasColumnName("ea_StatusCancelDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaStatusCancelIp)
                    .HasColumnName("ea_StatusCancelIP")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaTmpId)
                    .IsRequired()
                    .HasColumnName("ea_TmpID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaUpdateBy)
                    .HasColumnName("ea_UpdateBy")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaUpdateIp)
                    .HasColumnName("ea_UpdateIP")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaUserId)
                    .HasColumnName("ea_UserID")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.Kycno).HasColumnName("KYCNo");

                entity.Property(e => e.TokenId)
                    .HasColumnName("TokenID")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TbAccidentMasterLineCar>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLineCar");

                entity.Property(e => e.EaAccNo)
                    .HasColumnName("ea_AccNo")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarBand)
                    .HasColumnName("ea_CarBand")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarCancelDate)
                    .HasColumnName("ea_CarCancelDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarCancelStatus).HasColumnName("ea_CarCancelStatus");

                entity.Property(e => e.EaCarColor)
                    .HasColumnName("ea_CarColor")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarCushiNo)
                    .HasColumnName("ea_CarCushiNo")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFirstName)
                    .HasColumnName("ea_CarFirstName")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundCarBrand)
                    .HasColumnName("ea_CarFoundCarBrand")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundCarLicense)
                    .HasColumnName("ea_CarFoundCarLicense")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundCarProv)
                    .HasColumnName("ea_CarFoundCarProv")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundCarType)
                    .HasColumnName("ea_CarFoundCarType")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundChassisNo)
                    .HasColumnName("ea_CarFoundChassisNo")
                    .HasMaxLength(40)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundEffDate)
                    .HasColumnName("ea_CarFoundEffDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarFoundEnginesize).HasColumnName("ea_CarFoundEnginesize");

                entity.Property(e => e.EaCarFoundExpDate)
                    .HasColumnName("ea_CarFoundExpDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarFoundInsId)
                    .HasColumnName("ea_CarFoundInsId")
                    .HasMaxLength(5)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarFoundPolicyNo)
                    .HasColumnName("ea_CarFoundPolicyNo")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarGroup)
                    .HasColumnName("ea_CarGroup")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarInsertBy)
                    .HasColumnName("ea_CarInsertBy")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarInsertDate)
                    .HasColumnName("ea_CarInsertDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarInsertIp)
                    .HasColumnName("ea_CarInsertIP")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarLastUpdate)
                    .HasColumnName("ea_CarLastUpdate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarLicense)
                    .HasColumnName("ea_CarLicense")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarModel)
                    .HasColumnName("ea_CarModel")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarNo).HasColumnName("ea_CarNo");

                entity.Property(e => e.EaCarPolNo)
                    .HasColumnName("ea_CarPolNo")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarProv)
                    .HasColumnName("ea_CarProv")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarSearchStatus)
                    .HasColumnName("ea_CarSearchStatus")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.EaCarSurName)
                    .HasColumnName("ea_CarSurName")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarTitleName)
                    .HasColumnName("ea_CarTitleName")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarType)
                    .HasColumnName("ea_CarType")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarUpdateBy)
                    .HasColumnName("ea_CarUpdateBy")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaCarUpdateIp)
                    .HasColumnName("ea_CarUpdateIP")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaStatusNotCar)
                    .HasColumnName("ea_StatusNotCar")
                    .HasMaxLength(2);

                entity.Property(e => e.EaStatusNotCarInt)
                    .HasColumnName("ea_StatusNotCarInt")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.EaTmpId)
                    .HasColumnName("ea_TmpID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaUserId)
                    .HasColumnName("ea_UserID")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Kycno).HasColumnName("KYCNO");

                entity.Property(e => e.TokenId)
                    .HasColumnName("TokenID")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TbAccidentMasterLineVictim>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tb_AccidentMasterLineVictim");

                entity.Property(e => e.EaAccno)
                    .HasColumnName("ea_Accno")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.EaAddressVictim)
                    .HasColumnName("ea_AddressVictim")
                    .HasMaxLength(300)
                    .IsUnicode(false);

                entity.Property(e => e.EaAgeVictim).HasColumnName("ea_AgeVictim");

                entity.Property(e => e.EaAmphurVictim)
                    .HasColumnName("ea_AmphurVictim")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaBirthday)
                    .HasColumnName("ea_Birthday")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaBrokenDetail)
                    .HasColumnName("ea_BrokenDetail")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaBrokenVictim)
                    .HasColumnName("ea_BrokenVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaCancelDate)
                    .HasColumnName("ea_CancelDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCarNo).HasColumnName("ea_CarNo");

                entity.Property(e => e.EaChangwatVictim)
                    .HasColumnName("ea_ChangwatVictim")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaConfirmed)
                    .HasColumnName("ea_confirmed")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.EaConfirmedby)
                    .HasColumnName("ea_confirmedby")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaConfirmeddate)
                    .HasColumnName("ea_confirmeddate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaCountryVictim)
                    .HasColumnName("ea_CountryVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaDateDead)
                    .HasColumnName("ea_DateDead")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaDeadNo)
                    .HasColumnName("ea_DeadNo")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaFnameVictim)
                    .HasColumnName("ea_FnameVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaForeign).HasColumnName("ea_Foreign");

                entity.Property(e => e.EaHosRecDateTime)
                    .HasColumnName("ea_HosRecDateTime")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaIdCardType)
                    .HasColumnName("ea_IdCardType")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaIdCardVictim)
                    .HasColumnName("ea_IdCardVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaInsertBy)
                    .HasColumnName("ea_InsertBy")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaInsertDate)
                    .HasColumnName("ea_InsertDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaInsertIp)
                    .HasColumnName("ea_InsertIP")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaLastUpdate)
                    .HasColumnName("ea_LastUpdate")
                    .HasColumnType("datetime");

                entity.Property(e => e.EaLnameVictim)
                    .HasColumnName("ea_LnameVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaMooVictim)
                    .HasColumnName("ea_MooVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaNationalityId)
                    .HasColumnName("ea_NationalityId")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaPhoneNumber)
                    .HasColumnName("ea_PhoneNumber")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaPrefixVictim)
                    .HasColumnName("ea_PrefixVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaReferChangwat)
                    .HasColumnName("ea_ReferChangwat")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaReferCountry)
                    .HasColumnName("ea_ReferCountry")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaReferHospital)
                    .HasColumnName("ea_ReferHospital")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.EaRoadVictim)
                    .HasColumnName("ea_RoadVictim")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EaSexVictim)
                    .HasColumnName("ea_SexVictim")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.EaSoiVictim)
                    .HasColumnName("ea_SoiVictim")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaStatusCancel).HasColumnName("ea_StatusCancel");

                entity.Property(e => e.EaStatusVictim)
                    .HasColumnName("ea_StatusVictim")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaTmpId)
                    .HasColumnName("ea_TmpID")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaTumbolVictim)
                    .HasColumnName("ea_TumbolVictim")
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.EaUpdateBy)
                    .HasColumnName("ea_UpdateBy")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaUpdateIp)
                    .HasColumnName("ea_UpdateIP")
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.EaUserId)
                    .HasColumnName("ea_UserID")
                    .HasMaxLength(36)
                    .IsUnicode(false);

                entity.Property(e => e.EaVictimId)
                    .HasColumnName("ea_VictimId")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EaVictimNo).HasColumnName("ea_VictimNo");

                entity.Property(e => e.EaVictimType)
                    .HasColumnName("ea_VictimType")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Kycno).HasColumnName("KYCNO");

                entity.Property(e => e.TokenId)
                    .HasColumnName("TokenID")
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}