// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class ApprovalStatus
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    }
}