// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using DataAccess.EFCore.DigitalClaimModels;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class DigitalclaimContext
    {

        [DbFunction("fn_IDCardValidate", "dbo")]
        public static int? fn_IDCardValidate(string TypeCard, string IDCard)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
