// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class DigitalclaimContext : DbContext
    {
        public DigitalclaimContext()
        {
        }

        public DigitalclaimContext(DbContextOptions<DigitalclaimContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ApprovalStatus> ApprovalStatus { get; set; }
        public virtual DbSet<HosApproval> HosApproval { get; set; }
        public virtual DbSet<HosApprovalStatus> HosApprovalStatus { get; set; }
        public virtual DbSet<HosApprovalStatusState> HosApprovalStatusState { get; set; }
        public virtual DbSet<HosDocumentReceive> HosDocumentReceive { get; set; }
        public virtual DbSet<Invoicehd> Invoicehd { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ApprovalStatus>(entity =>
            {
                entity.HasKey(e => e.StatusId);

                entity.Property(e => e.StatusId).ValueGeneratedNever();

                entity.Property(e => e.StatusNameEclaim).HasMaxLength(50);

                entity.Property(e => e.StatusNameIclaim).HasMaxLength(50);
            });

            modelBuilder.Entity<HosApproval>(entity =>
            {
                entity.HasKey(e => new { e.AccNo, e.VictimNo, e.AppNo });

                entity.Property(e => e.AccNo)
                    .HasColumnName("AccNO")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.AcceptBy)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.AcceptDate).HasColumnType("datetime");

                entity.Property(e => e.BranchId)
                    .HasColumnName("BranchID")
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.CanCelStatus)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ClaimNo)
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.Property(e => e.DateCreate).HasColumnType("datetime");

                entity.Property(e => e.DocumentNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.GetRecordStatus)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.HosIdRefer)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.InvoiceId)
                    .HasColumnName("InvoiceID")
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.InvoiceNo)
                    .HasColumnName("InvoiceNO")
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.LastUpdate).HasColumnType("datetime");

                entity.Property(e => e.PayMore)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Pt4id)
                    .HasColumnName("PT4ID")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.RecFname)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RecLname)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RecPrefix)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RecRelate)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.RecSocNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.RegDate).HasColumnType("datetime");

                entity.Property(e => e.RegNoClaim).HasColumnName("RegNo_Claim");

                entity.Property(e => e.RegType)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.RevFname)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RevLname)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RevPrefix)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.RevRelate)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.UserId)
                    .HasColumnName("UserID")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VictimNoClaim).HasColumnName("VictimNo_Claim");
            });

            modelBuilder.Entity<HosApprovalStatus>(entity =>
            {
                entity.HasKey(e => new { e.AccNo, e.VictimNo, e.AppNo });

                entity.Property(e => e.AccNo)
                    .HasColumnName("AccNO")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.InsertDate).HasColumnType("datetime");

                entity.Property(e => e.LastUpdate).HasColumnType("datetime");
            });

            modelBuilder.Entity<HosApprovalStatusState>(entity =>
            {
                entity.HasKey(e => new { e.AccNo, e.VictimNo, e.AppNo, e.StateNo });

                entity.Property(e => e.AccNo)
                    .HasColumnName("AccNO")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.InsertDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<HosDocumentReceive>(entity =>
            {
                entity.HasKey(e => new { e.AccNo, e.VictimNo, e.Appno, e.RunNo });

                entity.Property(e => e.AccNo).HasMaxLength(20);

                entity.Property(e => e.AccountName)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.AccountNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.AccountType)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.BankBranch)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.BankId)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.BookBankFileName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.BookBankFilePath)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.BranchId)
                    .HasColumnName("BranchID")
                    .HasMaxLength(10);

                entity.Property(e => e.CheckDate).HasColumnType("datetime");

                entity.Property(e => e.DueNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.PaidImmediately)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.PaymentType)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ReceiveDate).HasColumnType("datetime");

                entity.Property(e => e.Regisdate).HasColumnType("datetime");

                entity.Property(e => e.TokenPrint)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TransferDate).HasColumnType("datetime");

                entity.Property(e => e.UserId)
                    .HasColumnName("UserID")
                    .HasMaxLength(10);
            });

            modelBuilder.Entity<Invoicehd>(entity =>
            {
                entity.HasKey(e => e.IdInvhd);

                entity.ToTable("invoicehd");

                entity.Property(e => e.IdInvhd)
                    .HasColumnName("id_invhd")
                    .ValueGeneratedNever();

                entity.Property(e => e.AccNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Age).HasColumnName("age");

                entity.Property(e => e.An)
                    .HasColumnName("AN")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BookNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Comment)
                    .HasColumnName("comment")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.Consider)
                    .HasColumnName("consider")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Daybed).HasColumnName("daybed");

                entity.Property(e => e.Dispensedate)
                    .HasColumnName("dispensedate")
                    .HasColumnType("datetime");

                entity.Property(e => e.Dispensetime)
                    .HasColumnName("dispensetime")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Hn)
                    .HasColumnName("HN")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Hosid)
                    .HasColumnName("hosid")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Hostype)
                    .HasColumnName("hostype")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.IdInvdt).HasColumnName("id_invdt");

                entity.Property(e => e.InputBy)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.InvoiceDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceNo)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.InvoiceType)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Maincomment)
                    .HasColumnName("maincomment")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.Mainconsider)
                    .HasColumnName("mainconsider")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.RecDate).HasColumnType("datetime");

                entity.Property(e => e.ReceiptDate).HasColumnType("datetime");

                entity.Property(e => e.ReceiptNo)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.RecordBy)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.RecordDate).HasColumnType("datetime");

                entity.Property(e => e.Suminv).HasColumnName("suminv");

                entity.Property(e => e.Takendate)
                    .HasColumnName("takendate")
                    .HasColumnType("datetime");

                entity.Property(e => e.Takentime)
                    .HasColumnName("takentime")
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.VictimType)
                    .HasMaxLength(3)
                    .IsUnicode(false);

                entity.Property(e => e.Victimname)
                    .HasColumnName("victimname")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Vname)
                    .HasColumnName("vname")
                    .HasMaxLength(10)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}