// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class HosDocumentReceive
    {
        public string AccNo { get; set; }
        public short VictimNo { get; set; }
        public short Appno { get; set; }
        public short RunNo { get; set; }
        public DateTime? ReceiveDate { get; set; }
        public DateTime? TransferDate { get; set; }
        public DateTime? Regisdate { get; set; }
        public string UserId { get; set; }
        public string BranchId { get; set; }
        public DateTime? CheckDate { get; set; }
        public string DueNo { get; set; }
        public string PaidImmediately { get; set; }
        public string PaymentType { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string BankId { get; set; }
        public string BankBranch { get; set; }
        public string AccountType { get; set; }
        public string BookBankFileName { get; set; }
        public string BookBankFilePath { get; set; }
        public string TokenPrint { get; set; }
    }
}