// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimCheckInvoiceDocuments
    {
        public int IdInvhd { get; set; }
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public int AppNo { get; set; }
        public string ReceiptNo { get; set; }
        public string InvoiceStatus { get; set; }
        public string InvoiceComment { get; set; }
    }
}