// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimApproval
    {
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public int AppNo { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? LastUpdate { get; set; }
        public int? Status { get; set; }
        public string BranchId { get; set; }
        public double? SumMoney { get; set; }
        public string PayMore { get; set; }
        public double? CureMoney { get; set; }
        public double? DeadMoney { get; set; }
        public double? HygieneMoney { get; set; }
        public double? CrippledMoney { get; set; }
        public string RevPrefix { get; set; }
        public string RevFname { get; set; }
        public string RevLname { get; set; }
        public string RevRelate { get; set; }
        public string RecPrefix { get; set; }
        public string RecFname { get; set; }
        public string RecLname { get; set; }
        public string RecRelate { get; set; }
        public string RecSocNo { get; set; }
        public string LineId { get; set; }
    }
}