// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimApproval
    {
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public int ReqNo { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? LastUpdate { get; set; }
        public int? Status { get; set; }
        public string BranchId { get; set; }
        public double? SumReqMoney { get; set; }
        public string PayMore { get; set; }
        public double? CureMoney { get; set; }
        public double? DeadMoney { get; set; }
        public double? HygieneMoney { get; set; }
        public double? CrippledMoney { get; set; }
        public string LineId { get; set; }
        public double? SumPayMoney { get; set; }
    }
}