// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimCheckDocuments
    {
        public string AccNo { get; set; }
        public int VictimNo { get; set; }
        public int ReqNo { get; set; }
        public string IdCardStatus { get; set; }
        public string IdCardComment { get; set; }
        public string BookbankStatus { get; set; }
        public string BookbankComment { get; set; }
        public string InvoiceStatus { get; set; }
        public string SumStatus { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}