// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimInvoiceStatus
    {
        public long IdInvhd { get; set; }
        public string AccNo { get; set; }
        public int? VictimNo { get; set; }
        public int? ReqNo { get; set; }
        public int? Status { get; set; }
        public DateTime? InsertDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string RecordBy { get; set; }
        public double? ReqMoney { get; set; }
        public double? PayMoney { get; set; }
        public string InvDocComment { get; set; }
        public string InvConfirmMoneyComment { get; set; }
    }
}