// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimInvoiceCutLists
    {
        public long IdInvhd { get; set; }
        public string AccNo { get; set; }
        public int? VictimNo { get; set; }
        public int? ReqNo { get; set; }
        public int CutListNo { get; set; }
        public string CutListName { get; set; }
        public double? CutListPrice { get; set; }
        public DateTime? InsertDate { get; set; }
        public string RecordBy { get; set; }
        public string Ip { get; set; }
    }
}