// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimMasterTypes
    {
        /// <summary>
        /// รหัสประเภท
        /// </summary>
        public int TypeId { get; set; }
        public int? ParentTypeId { get; set; }
        /// <summary>
        /// ชื่อประเภท
        /// </summary>
        public string TypeName { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 0: ไม่ใช้งาน, 1: ใช้งานอยู่
        /// </summary>
        public bool IsActive { get; set; }
    }
}