// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimApprovalStatus
    {
        public int StatusId { get; set; }
        public string StatusNameIclaim { get; set; }
        public string StatusNameEclaim { get; set; }
    }
}