// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.DigitalClaimModels
{
    public partial class IclaimInvoiceDtVerify
    {
        public long IdInvdt { get; set; }
        public int? Listno { get; set; }
        public long Treatid { get; set; }
        public double? InvPrice { get; set; }
        public double? PaidPrice { get; set; }
        public string Recordby { get; set; }
        public DateTime? Recorddate { get; set; }
        public string Ip { get; set; }
    }
}